### ISSUE TITLE
Scrolling SVG images doesn't work

### ISSUE THREAD

**Issue by woky** [Pauan/AutoScroll#5]
For instance, on load of this URL
  https://upload.wikimedia.org/wikipedia/commons/1/1a/SVG_example_markup_grid.svg
the following error is reported:

    Error in response to storage.get: TypeError: Cannot read property 'setProperty' of undefined
        at Object.callback (chrome-extension://occjjkgifpmdgodlplnacmkejpdionan/data/AutoScroll.js:165:14)
        at chrome-extension://occjjkgifpmdgodlplnacmkejpdionan/data/AutoScroll.js:4:22

**Comment by Pauan** [comment]
Thanks for reporting this.

It seems that it's rather difficult to display HTML nodes inside of SVG.

So I might not be able to fix this.

**Comment by Pauan** [comment]
I just released version 4.6 of AutoScroll, which adds in partial support for SVG.

It is now possible to scroll SVG documents.

However, the circular icon does not show up.

The reason is because SVG does not allow for positioning elements absolutely or in fixed position.
